providerUrl: https://ropsten.infura.io/v3/undefined
privateKey: fad9c8855b740a0b7ed4c221dbad0f33a83a49cad6b3fe8d5817ac83d38b6a19
Token:
  initialSupply: 10000
  name: TestToken1
  symbol: TT1
  decimals: 18
  openFrozen: true
  openMint: true
  openBurn: true